language: c
script: ./.travis_build.sh

# Compile on both MacOS and Linux
os:
    - osx
    - linux

# Compile using both gcc & clang
compiler:
    - gcc
    - clang

jobs:
    include:
        - os: linux
          dist: xenial
          compiler: gcc
        - os: linux
          dist: xenial
          compiler: clang
        - os: linux
          dist: bionic
          compiler: gcc
        - os: linux
          dist: bionic
          compiler: clang
    allow_failures:
        - os: osx

# Install dependencies
addons:
    apt:
        packages:
        - libusb-1.0-0-dev
        - libudev-dev
        - autopoint
        - faketime
        - libcmocka-dev
        - libhidapi-dev
    homebrew:
        packages:
        - libusb
        - gettext
        - cmocka
        - hidapi

# Ensure that build dependencies are available on OSX
before_script:
    - if [ "$TRAVIS_OS_NAME" = osx ]; then brew install libusb gettext cmocka hidapi; fi

# Enable parallel make
env:
    global:
        - MAKEFLAGS="-j 2"

